apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component
    app.kubernetes.io/part-of: test-app-167102285
  name: go-component
  namespace: ylp2gk7k
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-component
    weight: 100
status: {}
