apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app-167102285
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: go-component
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: go-component
  namespace: ylp2gk7k
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: go-component
status:
  configuration:
    generatedName: ""
