apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-quarkus
  namespace: ylp2gk7k
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app-167102285
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-quarkus-
      labels:
        build.appstudio.openshift.io/application: test-app-167102285
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: ylp2gk7k
    spec:
      params:
      - name: git-url
        value: https://github.com/dheerajodha/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:ylp2gk7k-java-quarkus-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/dheerajodha/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-quarkus/$(tt.params.git-revision)
    status: {}
status: {}
