apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: test-app-167102285
  name: nodejs
  namespace: ylp2gk7k
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs
status:
  loadBalancer: {}
